docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: v3/index.md
    - v3:
      - "RecordExists/NoRecordExists": v3/exists.md
site_name: 'laminas-db-validator'
site_description: 'laminas-db validators for laminas-validator'
repo_url: 'https://github.com/axleus/laminas-db-validator'
extra:
    project: Components
    installation:
        module_class: 'Laminas\Db\Validator\Module'
    current_version: v3
    versions:
      - v3
